RuralisBundle\Entity\Abonne:
    type: entity
    table: null
    repositoryClass: RuralisBundle\Repository\AbonneRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        rue:
            type: string
            length: 255
        cp:
            type: integer
        ville:
            type: string
            length: 255
        pays:
            type: string
            length: 255
        telephone:
            type: integer
        dateAbonnement:
            type: date
            column: date_abonnement
        newsletter:
            type: boolean
        abonne:
            type: boolean
        typeAbonnement:
            type: string
            length: 255
            column: type_abonnement
    lifecycleCallbacks: {  }
