RuralisBundle\Entity\Abonnement:
    type: entity
    table: null
    repositoryClass: RuralisBundle\Repository\AbonnementRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        newsletter:
            type: boolean
    lifecycleCallbacks: {  }
    manyToOne:
        contact:
            targetEntity: RuralisBundle\Entity\Contact
            cascade: ["persist", "remove"]

        type_abo:
            targetEntity: RuralisBundle\Entity\TypeAbo
            joinColumn:
                nullable: true
            cascade: ["persist", "remove"]

        abonne:
            targetEntity: RuralisBundle\Entity\Abonne
            joinColumn:
                nullable: true
            cascade: ["persist", "remove"]