RuralisBundle\Entity\Newsletter:
    type: entity
    table: null
    repositoryClass: RuralisBundle\Repository\NewsletterRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        contenu:
            type: text
        envoi:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
    manyToMany:
        abonnements:
            targetEntity: RuralisBundle\Entity\Abonnement