RuralisBundle\Entity\TypeAffichage:
    type: entity
    table: null
    repositoryClass: RuralisBundle\Repository\TypeAffichageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            nullable: true;
    lifecycleCallbacks: {  }
