RuralisBundle\Entity\TypeAbo:
    type: entity
    table: null
    repositoryClass: RuralisBundle\Repository\TypeAboRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255
    lifecycleCallbacks: {  }
