#Administration des Newsletter
newsletter_index:
    path:     /
    defaults: { _controller: "RuralisBundle:Newsletter:index" }
    methods:  GET

newsletter_show:
    path:     /{id}/show
    defaults: { _controller: "RuralisBundle:Newsletter:show" }
    methods:  GET

newsletter_new:
    path:     /new
    defaults: { _controller: "RuralisBundle:Newsletter:new" }
    methods:  [GET, POST]

newsletter_edit:
    path:     /{id}/edit
    defaults: { _controller: "RuralisBundle:Newsletter:edit" }
    methods:  [GET, POST]

newsletter_delete:
    path:     /{id}/delete
    defaults: { _controller: "RuralisBundle:Newsletter:delete" }
    methods:  GET

#Gestion abonnement/envoie Newsletter
ruralis_send_newsletter:
    path:     /{id}/sendnewsletter
    defaults: { _controller:  RuralisBundle:Newsletter:send }

ruralis_inscrits_newsletter:
    path:     /admin/inscritsnewsletter
    defaults: { _controller:  RuralisBundle:Admin:InscritsNewsletter }