newsletter_index:
    path:     /
    defaults: { _controller: "RuralisBundle:Newsletter:index" }
    methods:  GET

newsletter_show:
    path:     /{id}/show
    defaults: { _controller: "RuralisBundle:Newsletter:show" }
    methods:  GET

newsletter_new:
    path:     /new
    defaults: { _controller: "RuralisBundle:Newsletter:new" }
    methods:  [GET, POST]

newsletter_edit:
    path:     /{id}/edit
    defaults: { _controller: "RuralisBundle:Newsletter:edit" }
    methods:  [GET, POST]

newsletter_delete:
    path:     /{id}/delete
    defaults: { _controller: "RuralisBundle:Newsletter:delete" }
    methods:  DELETE
