# Routes User
ruralis_homepage:
    path:     /
    defaults: { _controller: RuralisBundle:ViewsUser:index, page:1 }

ruralis_presentation:
    path:     /ruralis
    defaults: { _controller: RuralisBundle:ViewsUser:ruralis }

ruralis_abonnement:
    path:     /abonnement
    defaults: { _controller: RuralisBundle:ViewsUser:abonnement }

ruralis_partenaire:
    path:     /partenaires
    defaults: { _controller: RuralisBundle:ViewsUser:partenaires }

ruralis_article:
    path:     /{id}/article
    defaults: { _controller: RuralisBundle:ViewsUser:article, id: null }

ruralis_formulaire_abonnement:
    path:     /{type}/formulaire
    defaults: { _controller: RuralisBundle:Formulaire:index, type: lecteur|donateur|ambassadeur}
    requirements:
        type: lecteur|donateur|ambassadeur

ruralis_recapitulatif_abo:
    path:     /recapitulatif
    defaults: { _controller:  RuralisBundle:Formulaire:recapAbo}
    methods:  [POST]

# Routes Admin
ruralis_admin_article:
    resource: "@RuralisBundle/Resources/config/routing/article.yml"
    prefix:   /article

ruralis_admin_partenaire:
    resource: "@RuralisBundle/Resources/config/routing/partenaire.yml"
    prefix:   /admin/partenaire
