# Routes User
ruralis_homepage:
    path:     /
    defaults: { _controller: RuralisBundle:ViewsUser:index, page:1 }

ruralis_presentation:
    path:     /ruralis
    defaults: { _controller: RuralisBundle:ViewsUser:ruralis }

ruralis_abonnement:
    path:     /abonnement
    defaults: { _controller: RuralisBundle:ViewsUser:abonnement }

ruralis_partenaire:
    path:     /partenaires
    defaults: { _controller: RuralisBundle:ViewsUser:partenaires }

ruralis_article:
    path:     /{id}/article
    defaults: { _controller: RuralisBundle:ViewsUser:article, id: null }

ruralis_formulaire_abonnement:
    path:     /{type}/formulaire
    defaults: { _controller: RuralisBundle:Formulaire:index, type: lecteur|donateur|ambassadeur}
    requirements:
        type: lecteur|donateur|ambassadeur

ruralis_recapitulatif_abo:
    path:     /recapitulatif
    defaults: { _controller:  RuralisBundle:Formulaire:recapAbo}
    methods:  [POST]

ruralis_send_newsletter:
    path:     /sendnewsletter
    defaults: { _controller:  RuralisBundle:Contact:send}
    methods:  [GET, POST]

# Routes

# Routes Admin
ruralis_admin:
    path:     /admin
    defaults: { _controller: RuralisBundle:Admin:admin }

ruralis_admin_article:
    resource: "@RuralisBundle/Resources/config/routing/article.yml"
    prefix:   /admin/article

ruralis_admin_partenaire:
    resource: "@RuralisBundle/Resources/config/routing/partenaire.yml"
    prefix:   /admin/partenaire

ruralis_admin_newsletter:
    resource: "@RuralisBundle/Resources/config/routing/newsletter.yml"
    prefix:   /admin/newsletter

#FOS USER
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile