ruralis_article:
    resource: "@RuralisBundle/Resources/config/routing/article.yml"
    prefix:   /admin/article

ruralis_typeaffichage:
    resource: "@RuralisBundle/Resources/config/routing/typeaffichage.yml"
    prefix:   /admin/typeaffichage

ruralis_homepage:
    path:     /
    defaults: { _controller: RuralisBundle:Default:index }

ruralis_presentation:
    path:     /ruralis
    defaults: { _controller: RuralisBundle:Ruralis:index }