# Routes User
ruralis_homepage:
    path:     /
    defaults: { _controller: RuralisBundle:Default:index, page:1 }

ruralis_presentation:
    path:     /ruralis
    defaults: { _controller: RuralisBundle:Ruralis:index }

ruralis_abonnement:
    path:     /abonnement
    defaults: { _controller: RuralisBundle:Abonnement:index }

ruralis_partenaire:
    path:     /partenaires
    defaults: { _controller: RuralisBundle:Partenaires:index }

ruralis_formulaire_abonnement:
  path:     /formulaire
  defaults: { _controller: RuralisBundle:Formulaire:index}


# Routes Admin
ruralis_admin_article:
    resource: "@RuralisBundle/Resources/config/routing/article.yml"
    prefix:   /article

ruralis_article:
    path:     /{id}/article
    defaults: { _controller: RuralisBundle:Default:article, id: null }

ruralis_admin_partenaire:
    resource: "@RuralisBundle/Resources/config/routing/partenaire.yml"
    prefix:   /admin/partenaire
