ruralis_article:
    resource: "@RuralisBundle/Resources/config/routing/article.yml"
    prefix:   /admin/article

ruralis_homepage:
    path:     /
    defaults: { _controller: RuralisBundle:Default:index, page:1 }

ruralis_presentation:
    path:     /ruralis
    defaults: { _controller: RuralisBundle:Ruralis:index }

ruralis_abonnement:
    path:     /abonnement
    defaults: { _controller: RuralisBundle:Abonnement:index }

ruralis_partenaire:
    path:     /partenaires
    defaults: { _controller: RuralisBundle:Partenaires:index }

ruralis_admin_partenaire:
    resource: "@RuralisBundle/Resources/config/routing/partenaire.yml"
    prefix:   /admin/partenaire