# Routes USER

# HOME
ruralis_homepage:
    path:     /
    defaults: { _controller: RuralisBundle:ViewsUser:index, page:1 }

# RURALIS
ruralis_presentation:
    path:     /ruralis
    defaults: { _controller: RuralisBundle:ViewsUser:ruralis }

# ABONNMENT
ruralis_abonnement:
    path:     /abonnement
    defaults: { _controller: RuralisBundle:ViewsUser:abonnement }

ruralis_formulaire_abonnement:
    path:     /{type}/formulaire
    defaults: { _controller: RuralisBundle:Formulaire:index, type: lecteur|donateur|ambassadeur}
    requirements:
        type: lecteur|donateur|ambassadeur

ruralis_recapitulatif_abo:
    path:     /recapitulatif
    defaults: { _controller:  RuralisBundle:Formulaire:recapAbo}
    methods:  [POST]

ruralis_abonnes:
    path:     /admin/abonnes
    defaults: { _controller:  RuralisBundle:Admin:abonnes }

# PARTENAIRES
ruralis_partenaire:
    path:     /partenaires
    defaults: { _controller: RuralisBundle:ViewsUser:partenaires }

# BLOG
ruralis_article:
    path:     /{id}/article
    defaults: { _controller: RuralisBundle:ViewsUser:article, id: null }

# NEWSLETTER

ruralis_inscription_newsletter:
    path:     /inscriptionnewsletter
    defaults: { _controller:  RuralisBundle:Contact:inscription}
    methods:  [GET, POST]

ruralis_inscrits_newsletter:
    path:     /admin/inscritsnewsletter
    defaults: { _controller:  RuralisBundle:Admin:InscritsNewsletter }

ruralis_inscrits_magazine:
    path:     /admin/inscritsmagazine
    defaults: { _controller:  RuralisBundle:Admin:InscritsMagazine }

ruralis_template_newsletter:
    path:     /{id}/newsletter
    defaults: { _controller:  RuralisBundle:ViewsUser:templateNewsletter, id: null}

# Routes

# Routes Admin
ruralis_admin:
    path:     /admin
    defaults: { _controller: RuralisBundle:Admin:admin }

ruralis_admin_article:
    resource: "@RuralisBundle/Resources/config/routing/article.yml"
    prefix:   /admin/article

ruralis_admin_partenaire:
    resource: "@RuralisBundle/Resources/config/routing/partenaire.yml"
    prefix:   /admin/partenaire

ruralis_admin_newsletter:
    resource: "@RuralisBundle/Resources/config/routing/newsletter.yml"
    prefix:   /admin/newsletter

ruralis_send_newsletter:
    path:     /{id}/sendnewsletter
    defaults: { _controller:  RuralisBundle:Newsletter:send, id: null }

#FOS USER
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

ruralis_abosend:
    path:     /validationabonnment
    defaults: { _controller:  RuralisBundle:Contact:abosend, details: null }
    methods:  [GET, POST]

ruralis_aboannul:
    path:     /annulationabonnement
    defaults: { _controller:  RuralisBundle:Contact:aboannul}
    methods:  [GET, POST]