# Routes Admin
ruralis_admin:
    path:     /admin
    defaults: { _controller: RuralisBundle:Admin:admin }

ruralis_admin_article:
    resource: "@RuralisBundle/Resources/config/routing/article.yml"
    prefix:   /admin/article

ruralis_admin_partenaire:
    resource: "@RuralisBundle/Resources/config/routing/partenaire.yml"
    prefix:   /admin/partenaire

ruralis_admin_newsletter:
    resource: "@RuralisBundle/Resources/config/routing/newsletter.yml"
    prefix:   /admin/newsletter

ruralis_admin_magazine:
    resource: "@RuralisBundle/Resources/config/routing/magazineAbo.yml"
    prefix:   /admin/magazine