RuralisBundle\Entity\Image:
    properties:
        file:
            - File:
                maxSize: 2M
                mimeTypes: [application/pdf, application/x-pdf]
                mimeTypesMessage: "Merci de proposer un fichier PDF valide"
