RuralisBundle\Entity\Image:
    properties:
        file:
            - File:
                maxSize: 2M
                mimeTypes: [image/*]
                mimeTypesMessage: "Merci de proposer une image valide"
